# Generated by Django 3.1 on 2021-04-21 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=150, verbose_name='наименование товара')),
                ('date_receipt', models.DateField(default=datetime.datetime(2021, 4, 21, 22, 35, 56, 504409), verbose_name='дата поступления')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='цена')),
                ('unit', models.IntegerField(choices=[(1, 'шт.'), (2, 'кг.')], default=(1, 'шт.'), verbose_name='единица измерения')),
                ('supplier', models.CharField(blank=True, max_length=256, verbose_name='имя поставщика')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
